data:
  train:
    input: 
      precip: /work/FAC/FGSE/IDYST/tbeucler/downscaling/sasthana/Downscaling/Downscaling_Models/Training_Dataset_50km_SR_1971_2023/RhiresD_input_train_chronological_scaled.nc
      temp: /work/FAC/FGSE/IDYST/tbeucler/downscaling/sasthana/Downscaling/Downscaling_Models/Training_Dataset_50km_SR_1971_2023/TabsD_input_train_chronological_scaled.nc
      temp_min: /work/FAC/FGSE/IDYST/tbeucler/downscaling/sasthana/Downscaling/Downscaling_Models/Training_Dataset_50km_SR_1971_2023/TminD_input_train_chronological_scaled.nc
      temp_max: /work/FAC/FGSE/IDYST/tbeucler/downscaling/sasthana/Downscaling/Downscaling_Models/Training_Dataset_50km_SR_1971_2023/TmaxD_input_train_chronological_scaled.nc
    target:
      precip: /work/FAC/FGSE/IDYST/tbeucler/downscaling/sasthana/Downscaling/Downscaling_Models/Training_Dataset_50km_SR_1971_2023/RhiresD_target_train_chronological_scaled.nc
      temp: /work/FAC/FGSE/IDYST/tbeucler/downscaling/sasthana/Downscaling/Downscaling_Models/Training_Chronological_Dataset/TabsD_target_train_chronological_scaled.nc
      temp_min: /work/FAC/FGSE/IDYST/tbeucler/downscaling/sasthana/Downscaling/Downscaling_Models/Training_Chronological_Dataset/TminD_target_train_chronological_scaled.nc
      temp_max: /work/FAC/FGSE/IDYST/tbeucler/downscaling/sasthana/Downscaling/Downscaling_Models/Training_Chronological_Dataset/TmaxD_target_train_chronological_scaled.nc

  val:
    input:
      precip: /work/FAC/FGSE/IDYST/tbeucler/downscaling/sasthana/Downscaling/Downscaling_Models/Training_Dataset_50km_SR_1971_2023/RhiresD_input_val_chronological_scaled.nc
      temp: /work/FAC/FGSE/IDYST/tbeucler/downscaling/sasthana/Downscaling/Downscaling_Models/Training_Dataset_50km_SR_1971_2023/TabsD_input_val_chronological_scaled.nc
      temp_min: /work/FAC/FGSE/IDYST/tbeucler/downscaling/sasthana/Downscaling/Downscaling_Models/Training_Dataset_50km_SR_1971_2023/TminD_input_val_chronological_scaled.nc
      temp_max: /work/FAC/FGSE/IDYST/tbeucler/downscaling/sasthana/Downscaling/Downscaling_Models/Training_Dataset_50km_SR_1971_2023/TmaxD_input_val_chronological_scaled.nc
    target:
      precip: /work/FAC/FGSE/IDYST/tbeucler/downscaling/sasthana/Downscaling/Downscaling_Models/Training_Dataset_50km_SR_1971_2023/RhiresD_target_val_chronological_scaled.nc
      temp: /work/FAC/FGSE/IDYST/tbeucler/downscaling/sasthana/Downscaling/Downscaling_Models/Training_Dataset_50km_SR_1971_2023/TabsD_target_val_chronological_scaled.nc
      temp_min: /work/FAC/FGSE/IDYST/tbeucler/downscaling/sasthana/Downscaling/Downscaling_Models/Training_Dataset_50km_SR_1971_2023/TminD_target_val_chronological_scaled.nc
      temp_max: /work/FAC/FGSE/IDYST/tbeucler/downscaling/sasthana/Downscaling/Downscaling_Models/Training_Dataset_50km_SR_1971_2023/TmaxD_target_val_chronological_scaled.nc

  test:
    input:
      precip: /work/FAC/FGSE/IDYST/tbeucler/downscaling/sasthana/Downscaling/Downscaling_Models/Training_Dataset_50km_SR_1971_2023/RhiresD_input_test_chronological_scaled.nc
      temp: /work/FAC/FGSE/IDYST/tbeucler/downscaling/sasthana/Downscaling/Downscaling_Models/Training_Dataset_50km_SR_1971_2023/TabsD_input_test_chronological_scaled.nc
      temp_min: /work/FAC/FGSE/IDYST/tbeucler/downscaling/sasthana/Downscaling/Downscaling_Models/Training_Dataset_50km_SR_1971_2023/TminD_input_test_chronological_scaled.nc
      temp_max: /work/FAC/FGSE/IDYST/tbeucler/downscaling/sasthana/Downscaling/Downscaling_Models/Training_Dataset_50km_SR_1971_2023/TmaxD_input_test_chronological_scaled.nc
    target:
      precip: /work/FAC/FGSE/IDYST/tbeucler/downscaling/sasthana/Downscaling/Downscaling_Models/Training_Dataset_50km_SR_1971_2023/RhiresD_target_test_chronological_scaled.nc
      temp: /work/FAC/FGSE/IDYST/tbeucler/downscaling/sasthana/Downscaling/Downscaling_Models/Training_Dataset_50km_SR_1971_2023/TabsD_target_test_chronological_scaled.nc
      temp_min: /work/FAC/FGSE/IDYST/tbeucler/downscaling/sasthana/Downscaling/Downscaling_Models/Training_Dataset_50km_SR_1971_2023/TminD_target_test_chronological_scaled.nc
      temp_max: /work/FAC/FGSE/IDYST/tbeucler/downscaling/sasthana/Downscaling/Downscaling_Models/Training_Dataset_50km_SR_1971_2023/TmaxD_target_test_chronological_scaled.nc

  static:
    elevation: /work/FAC/FGSE/IDYST/tbeucler/downscaling/sasthana/Downscaling/Downscaling_Models/elevation.tif