defaults:
  - paths: paths.yaml
  - _self_

experiment:
  batch_size: 32
  num_workers: 4

variables:
  input:
    precip: RhiresD
    temp: TabsD
    temp_min: TminD
    temp_max: TmaxD
  target:
    precip: RhiresD
    temp: TabsD
    temp_min: TminD
    temp_max: TmaxD

preprocessing:
  nan_to_num: true
  nan_value : 0.0

data:
  train:
    input: ${paths.data.train.input}
    target: ${paths.data.train.target}
  val:
    input: ${paths.data.val.input}
    target: ${paths.data.val.target}
  test:
    input: ${paths.data.test.input}
    target: ${paths.data.test.target}
  static:
    elevation: ${paths.data.static.elevation}

encoder:
  _target_: Training_LDM_conditional.models.components.ae.SimpleConvEncoder
  in_dim: 4
  levels: 2
  min_ch: 16
  ch_mult: 4

decoder:
  _target_: Training_LDM_conditional.models.components.ae.SimpleConvDecoder
  in_dim: 64
  levels: 2
  min_ch: 16



sampler:
  _target_: Training_LDM_conditional.models.components.ldm.denoiser.DDIMSampler
  model: ${denoiser}
  schedule: "linear"
  device: "cuda"
  ddim_num_steps: 250
  ddim_eta: 0.0


ema:
  _target_: Training_LDM_conditional.models.components.ldm.denoiser.LitEma
  model: ${denoiser}
  decay: 0.9999
  use_num_updates: true

datamodule:
  _target_: Training_LDM_conditional.DownscalingDataModule.DownscalingDataModule #Path to the exact class, not the module file : AsthanaSh
  train_input: ${data.train.input}
  train_target: ${data.train.target}
  val_input: ${data.val.input}
  val_target: ${data.val.target}
  test_input: ${data.test.input}
  test_target: ${data.test.target}
  elevation: ${data.static.elevation} #Added elevation to datamodule for context conditioning : AsthanaSh
  batch_size: ${experiment.batch_size}
  num_workers: ${experiment.num_workers}
  preprocessing:
    variables: ${variables}
    preprocessing: ${preprocessing}

  
callbacks:
  early_stopping:
    _target_: lightning.pytorch.callbacks.EarlyStopping
    monitor: val/loss
    patience: 10
    mode: min
  model_checkpoint:
    _target_: lightning.pytorch.callbacks.ModelCheckpoint
    dirpath: Training_LDM_conditional/trained_ckpts
    filename: LDM_checkpoint_V1_linear_schedule_250_steps
    save_top_k: 1
    monitor: val/loss
    mode: min

conditioner:
  _target_: Training_LDM_conditional.models.components.ldm.conditioner.AFNOConditionerNetBase
  autoencoder: ??? #Conditions with the VAE encoder output : AsthanaSh 
  embed_dim: 32
  embed_dim_out: 32
  analysis_depth: 4
  forecast_depth: 4
  input_size_ratios: [1]
  train_autoenc: false
  afno_fusion: false


denoiser:
  _target_: Training_LDM_conditional.models.components.ldm.denoiser.UNetModel
  in_channels: 32 #Matching VAE latent channels : AsthanaSh
  out_channels: 32
  model_channels: 64
  num_res_blocks: 2
  attention_resolutions: [1,2,4]
  context_ch: [32,32,32,32] #Conditioning with AFNO conditioner output : AsthanaSh
  channel_mult: [1,2,4,4]
  conv_resample: true
  dims: 2
  use_fp16: false
  num_heads: 4

model:
#Need to pass VAE autoencoder , not encoder and decoder : AsthanaSh
  _target_: Training_LDM_conditional.models.ldm_module.LatentDiffusion
  denoiser: ${denoiser}
  autoencoder:
    _target_: Training_LDM_conditional.models.ae_module.AutoencoderKL
    encoder: ${encoder}
    decoder: ${decoder}
    unet_regr: Training_LDM_conditional/trained_ckpts/Training_LDM.models.components.unet.DownscalingUnetLightning_checkpoint.ckpt
  context_encoder: ${conditioner}  #Conditions the denoiser with Unet prediction : AsthanaSh
  #VAE ckpt loaded from the ae_load_state_file 
  ae_load_state_file: Training_LDM_conditional/trained_ckpts/Training_LDM.models.ae_module.AutoencoderKL_checkpoint.ckpt
  #Note : Output from LDM : [batch_size, 4, height, width] (AsthanaSh)
  parameterization: "eps"
  loss_type: "l2"
  timesteps: 250